### ISSUE TITLE
Documentation / Modules: The same non-informative tooltip for all modules icons and links

### ISSUE THREAD

**Issue by Nata11ia** [bootique/bootique-io#5]
"Modules (in alphabetical order)" tooltip is displayed on hover for all icons and links in Modules area:

![1](https://user-images.githubusercontent.com/23213832/28110137-18010f7e-66fa-11e7-9bab-477136a1a049.png)

**Comment by yharachka** [comment]
A similar issue is on the GET STARTED and CLA pages. A redundant tooltip appears on all elements (text, headers, links)

**Comment by IRus** [comment]
Fixed on docs and cla. Get started, core, jetty, logback - won't fix.
