### ISSUE TITLE
Github Stars: Counter value is not updated at once it was changed 

### ISSUE THREAD

**Issue by Nata11ia** [bootique/bootique-io#7]
OS X Chrome 59.0, Safari 10.1.1, Firefox 54.0.

**Steps:**

0. https://bootique.github.io/bootique-io/
1. Click on GitHub stars
-> https://github.com/bootique/bootique/stargazers is opened
2. Change value (Star/ Unstar)
3. Backspace to https://bootique.github.io/bootique-io/
-> old stars counter value is displayed
4. Reload page
-> old stars counter value is displayed
5. Open in any other browser
-> old stars counter value is displayed

Only after some delay stars counter value will be updated.

![1](https://user-images.githubusercontent.com/23213832/28111507-5d8e0a66-66fe-11e7-9bca-cb61907bba2d.png)

![2](https://user-images.githubusercontent.com/23213832/28111505-5d7dd128-66fe-11e7-91b5-503565a41ea3.png)

**Comment by IRus** [comment]
This is because Github API caches old value for some time. I doesn't think that this is bad for UX so I'll close issue.
