### ISSUE TITLE
Favicon is missed

### ISSUE THREAD

**Issue by Nata11ia** [bootique/bootique-io#8]
![1](https://user-images.githubusercontent.com/23213832/28112053-4eb80116-6700-11e7-9658-a6364da87400.png)

**Comment by IRus** [comment]
Fixed.

**Comment by Nata11ia** [comment]
@IRus it's fixed only for home page.
Reproduced for:
GET STARTED  
DOCUMENTATION  
CLA  
and https://www.objectstyle.com/f/cla/icla.pdf

**Comment by IRus** [comment]
@Nata11ia we moved site from github.io to bootique.io, so get started/cla/documentation should be fixed.
https://www.objectstyle.com/f/cla/icla.pdf - file, and he shouldn't have any favicon (or have objectstyle.com favicon)
